<a href="https://colab.research.google.com/github/NAGADEEP92/AI-ML-DS/blob/main/KerasNLP_gio_ext_KerasNLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q tensorflow==2.12.0
!pip install -q keras-nlp

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-text 2.13.0 requires tensorflow<2.14,>=2.13.0; platform_machine != "arm64" or platform_system != "Darwin", but you have tensorflow 2.12.0 which is incompatible.


In [ ]:
import keras_nlp

import numpy as np
from tensorflow import keras
import tensorflow as tf

Using TensorFlow backend


# Understand Tokenizer and Preprocessor

In [ ]:
gpt2_tokenizer = keras_nlp.models.GPT2Tokenizer.from_preset("gpt2_base_en")
gpt2_preprocessor = keras_nlp.models.GPT2CausalLMPreprocessor.from_preset("gpt2_base_en")

In [ ]:
text = "In case I don't see you, I wish you good morning good evening and good night!"

print(gpt2_tokenizer(text))
print(gpt2_preprocessor(text))

tf.Tensor(
[ 818 1339  314  836  470  766  345   11  314 4601  345  922 3329  922
 6180  290  922 1755    0], shape=(19,), dtype=int32)
({'token_ids': <tf.Tensor: shape=(1024,), dtype=int32, numpy=array([50256,   818,  1339, ...,     0,     0,     0], dtype=int32)>, 'padding_mask': <tf.Tensor: shape=(1024,), dtype=bool, numpy=array([ True,  True,  True, ..., False, False, False])>}, <tf.Tensor: shape=(1024,), dtype=int32, numpy=array([ 818, 1339,  314, ...,    0,    0,    0], dtype=int32)>, <tf.Tensor: shape=(1024,), dtype=bool, numpy=array([ True,  True,  True, ..., False, False, False])>)


In [ ]:
text = "Our base is under attack"
gpt2_causal_lm = keras_nlp.models.GPT2CausalLM.from_preset("gpt2_base_en")
print(gpt2_causal_lm.predict([text]))

1/1 [==============================] - 12s 12s/step
[[[ -43.431675  -39.836388  -43.06596  ...  -54.08771   -54.345146
    -42.364426]
  [ -83.18128   -83.162834  -84.15775  ...  -81.793     -86.67057
    -81.42278 ]
  [ -83.46461   -85.13437   -87.51859  ...  -89.97475   -92.49893
    -85.279175]
  ...
  [ -99.601326 -101.78831  -101.03879  ... -110.80366  -109.992546
    -96.18485 ]
  [ -99.72859  -101.900696 -101.15391  ... -110.91749  -110.1125
    -96.304634]
  [ -87.54201   -88.00072   -86.20575  ...  -97.40389   -95.16852
    -85.28137 ]]]


In [ ]:
custom_preprocessor = keras_nlp.models.GPT2CausalLMPreprocessor.from_preset(
    "gpt2_base_en",
    sequence_length=8,
)
gpt2_causal_lm.preprocessor = custom_preprocessor
print(gpt2_causal_lm.predict([text]))

1/1 [==============================] - 16s 16s/step
[[[ -43.431686  -39.83641   -43.06595  ...  -54.087673  -54.345158
    -42.36443 ]
  [ -83.181274  -83.162895  -84.15776  ...  -81.79299   -86.670715
    -81.422775]
  [ -83.464615  -85.134384  -87.5186   ...  -89.97461   -92.49892
    -85.27922 ]
  ...
  [ -96.977776 -101.5462   -105.414856 ... -113.38185  -114.144875
   -101.33536 ]
  [ -91.51218   -84.49864   -86.9746   ... -104.815414 -105.66455
    -92.898636]
  [ -85.723175  -86.26405   -83.614204 ...  -96.93444   -94.530716
    -84.692696]]]


In [ ]:
preprocessed_text = gpt2_preprocessor([text])
gpt2_causal_lm.preprocessor = None
print(gpt2_causal_lm.predict(preprocessed_text[0]))

1/1 [==============================] - 5s 5s/step
[[[ -43.431675  -39.836388  -43.06596  ...  -54.08771   -54.345146
    -42.364426]
  [ -83.18128   -83.162834  -84.15775  ...  -81.793     -86.67057
    -81.42278 ]
  [ -83.46461   -85.13437   -87.51859  ...  -89.97475   -92.49893
    -85.279175]
  ...
  [ -99.601326 -101.78831  -101.03879  ... -110.80366  -109.992546
    -96.18485 ]
  [ -99.72859  -101.900696 -101.15391  ... -110.91749  -110.1125
    -96.304634]
  [ -87.54201   -88.00072   -86.20575  ...  -97.40389   -95.16852
    -85.28137 ]]]


# Generate Text and Custom Sampler


In [ ]:
gpt2_causal_lm = keras_nlp.models.GPT2CausalLM.from_preset("gpt2_base_en")
gpt2_causal_lm.generate("I think basketball is fun because", max_length=50)

"I think basketball is fun because it is the game of basketball. It doesn't matter how you're playing, how you score and how many shots you shoot, you can't win a championship. That's just the way things are. If you"

In [ ]:
# Use contrastive search.
gpt2_causal_lm.compile(sampler="contrastive")
gpt2_causal_lm.generate("I think basketball is fun because", max_length=50)

"I think basketball is fun because it's fun to watch. It's fun to watch the game. It's fun to watch the game. It's fun to watch the game. It's fun to watch the game. It's fun to watch"

In [ ]:
# Use custom sampler configurations.
sampler = keras_nlp.samplers.TopPSampler(p=0.1)
gpt2_causal_lm.compile(sampler=sampler)
gpt2_causal_lm.generate("I think basketball is fun because", max_length=50)

"I think basketball is fun because it's fun to watch. It's fun to watch the game. It's fun to watch the game. It's fun to watch the game. It's fun to watch the game. It's fun to watch"

# Finetune your model

Let's try finetuning our GPT2 model with Dolly2 dataset.

In [ ]:
!pip install -q datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 486.2/486.2 kB 23.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 12.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.5/212.5 kB 20.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.3/134.3 kB 14.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 28.5 MB/s eta 0:00:00


In [ ]:
# Load Dolly2 from HuggingFace
from datasets import load_dataset

dolly = load_dataset("databricks/databricks-dolly-15k", split="train")

Extracting data files:   0%|          | 0/1 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Dataset json downloaded and prepared to /root/.cache/huggingface/datasets/databricks___json/databricks--databricks-dolly-15k-7427aa6e57c34282/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96. Subsequent calls will reuse this data.


In [ ]:
print(dolly[0])

{'instruction': 'When did Virgin Australia start operating?', 'context': "Virgin Australia, the trading name of Virgin Australia Airlines Pty Ltd, is an Australian-based airline. It is the largest airline by fleet size to use the Virgin brand. It commenced services on 31 August 2000 as Virgin Blue, with two aircraft on a single route. It suddenly found itself as a major airline in Australia's domestic market after the collapse of Ansett Australia in September 2001. The airline has since grown to directly serve 32 cities in Australia, from hubs in Brisbane, Melbourne and Sydney.", 'response': 'Virgin Australia commenced services on 31 August 2000 as Virgin Blue, with two aircraft on a single route.', 'category': 'closed_qa'}


In [ ]:
prompt_template = {
    "prompt_input": "Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\n{instruction}\n\n### Input:\n{input}\n\n### Response:\n{response}",
    "prompt_no_input": "Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\n{instruction}\n\n### Response:\n{response}",
}

In [ ]:
def format_text(data):
    if len(data["context"]) == 0:
        full_text = prompt_template["prompt_no_input"].format(
            instruction=data["instruction"],
            input=data["context"],
            response=data["response"],
        )
    else:
        full_text = prompt_template["prompt_input"].format(
            instruction=data["instruction"],
            input=data["context"],
            response=data["response"],
        )

    return full_text

In [ ]:
dolly_text = []
for data in dolly:
    dolly_text.append(format_text(data))

In [ ]:
dolly_tf_data = tf.data.Dataset.from_tensor_slices(dolly_text)
dolly_tf_data = dolly_tf_data.batch(4).cache().prefetch(tf.data.AUTOTUNE)

In [ ]:
# To speed up training and generation, we use preprocessor of length 512
# instead of full length 1024.
preprocessor = keras_nlp.models.GPT2CausalLMPreprocessor.from_preset(
    "gpt2_base_en",
    sequence_length=512,
)
gpt2_causal_lm = keras_nlp.models.GPT2CausalLM.from_preset(
    "gpt2_base_en", preprocessor=preprocessor
)

In [ ]:
num_epochs = 2
lr = tf.keras.optimizers.schedules.PolynomialDecay(
    5e-5,
    decay_steps=dolly_tf_data.cardinality() * num_epochs,
    end_learning_rate=0.0,
)
gpt2_causal_lm.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.AdamW(lr, weight_decay=0.001),
)

In [ ]:
gpt2_causal_lm.fit(dolly_tf_data.take(100), epochs=num_epochs)

Epoch 1/2
100/100 [==============================] - 112s 485ms/step - loss: 0.9166
Epoch 2/2
100/100 [==============================] - 49s 484ms/step - loss: 0.7895


In [ ]:
gpt2_causal_lm.generate("Why is basketball interesting?", max_length=100)

'Why is basketball interesting?\n\nIt is interesting because, like any other game, the game can change quickly. It is also interesting because the rules of basketball change as the game progresses and as the game progresses.\n\nThere are many different styles of basketball, but there are three main styles of basketball that are used in each of the four divisions:\n\n- Basketball with an A: Basketball with an B: Basketball with an A-\n\nThere are three types of basketball:\n'